### ISSUE TITLE
Navbar doen't update based on current notes date

### ISSUE THREAD

**Issue by xRyul** [karstenpedersen/obsidian-daily-note-navbar#10]
Great plugin, many thanks! 

Currently, navbar only updates if I use its buttons to navigate through different dates. 

But for instance if I click the arrows 2x to the previous week. And then manually open any Daily Note from the past.  The navbar still remembers those 2x clicks. But I think instead - it should automatically recognise appropriate week based on current notes title?

So for instance todays date is 2024-06-26:
<img width="735" alt="image" src="https://github.com/karstenpedersen/obsidian-daily-note-navbar/assets/47340038/36a3b819-a561-4bed-b33e-b9057aa6309b">

Then I try to go back by 2 weeks via navbar (but without actually opening that date):
<img width="746" alt="image" src="https://github.com/karstenpedersen/obsidian-daily-note-navbar/assets/47340038/caf2efbd-5fb2-47da-9fca-f3bf8a2e86ce">

Now I open any OLD daily note e.g.: 2024-04-01
The navbar now has dates of 2024-03-18 - 2024-03-24
<img width="748" alt="image" src="https://github.com/karstenpedersen/obsidian-daily-note-navbar/assets/47340038/b2c77dd1-7bed-49cd-896a-96fea46ce6d7">

but instead it should be 2024-04-01 - 2024-04-07:
<img width="750" alt="image" src="https://github.com/karstenpedersen/obsidian-daily-note-navbar/assets/47340038/765a86d4-686d-494a-822e-e7b6528d50a1">

**Comment by karstenpedersen** [comment]
Thanks for the feedback :)
I now reset the week offset when the active leaf changes.
