### ISSUE TITLE
[FR] Supporting Hover Editor and/or Open In New Window

### ISSUE THREAD

**Issue by Moyf** [karstenpedersen/obsidian-daily-note-navbar#11]
Hi! I love this plugin, very useful.

Could you consider adding support for Page Preview(Obsidian) / Hover Editor(Plugint) like when holding Ctrl and move over the button, show the preview:
![image](https://github.com/karstenpedersen/obsidian-daily-note-navbar/assets/4013062/a264b157-fd17-46ac-aca4-b084f8853241)

Or, could you add right-click menu to open the page in new window (and other ways)?
![image](https://github.com/karstenpedersen/obsidian-daily-note-navbar/assets/4013062/a1f1ff17-5168-488b-8c56-cf270ceb7722)

**Comment by karstenpedersen** [comment]
Hi, thanks for the feedback. I have added a context menu to the navbar, so you can pick where to open the files. I have also added an item here to copy the Obsidian URL, as that was easy to do.

There are also now settings for picking the default behaviour on how to open them.

If you have more ideas for features, and/or things that can go in the context menu, then you are welcome to create more issues :)

I tried looking at Hover Editor plugin, or just adding markdown preview on hover, but that might take some time for me to get right. I don't know if Hover Editor has an API, so other developers can use it, but I will look into it.

You can see the new version with context menu here:
https://github.com/karstenpedersen/obsidian-daily-note-navbar/releases/tag/0.1.7

**Comment by Moyf** [comment]
> Hi, thanks for the feedback. I have added a context menu to the navbar, so you can pick where to open the files. I have also added an item here to copy the Obsidian URL, as that was easy to do.
> 
> There are also now settings for picking the default behaviour on how to open them.
> 
> If you have more ideas for features, and/or things that can go in the context menu, then you are welcome to create more issues :)
> 
> I tried looking at Hover Editor plugin, or just adding markdown preview on hover, but that might take some time for me to get right. I don't know if Hover Editor has an API, so other developers can use it, but I will look into it.
> 
> You can see the new version with context menu here: https://github.com/karstenpedersen/obsidian-daily-note-navbar/releases/tag/0.1.7

Thank you for developing so quickly, this is a pleasant surprise!  :D 
I've updated to new version and it works great! 

For now the <kbd>Middle Mouse Button</kbd> would also trigger the context menu (same with Right Mouse Button), maybe changing it to `Open in new tab` would be more consistency with native link operation?

---

As for the Hover Editor, I guess it would just override the Obsidian's native preview feature. 🤔
So maybe just supporting Page Preview and the plugin itself would do the other things (I hope so, haha)

**Comment by karstenpedersen** [comment]
I am now using Obsidians ModEvents, so you can now press Ctrl+click or middle mouse button for new tab. You can also press Ctrl+shift+alt+click to open them in windows, or Ctr+alt+click to open in split. The context menu is now only opened with the right mouse button.

The normal clicks behaviour can still be changed in the settings tab.

https://github.com/karstenpedersen/obsidian-daily-note-navbar/releases/tag/0.1.9

---

I will wait a bit with the preview, as I first want to make the navbars responsive, so they only show dates that fit on the screen.

**Comment by Moyf** [comment]
> I am now using Obsidians ModEvents, so you can now press Ctrl+click or middle mouse button for new tab. You can also press Ctrl+shift+alt+click to open them in windows, or Ctr+alt+click to open in split. The context menu is now only opened with the right mouse button.
> 
> The normal clicks behaviour can still be changed in the settings tab.
> 
> https://github.com/karstenpedersen/obsidian-daily-note-navbar/releases/tag/0.1.9
> 
> I will wait a bit with the preview, as I first want to make the navbars responsive, so they only show dates that fit on the screen.

Wow that's amazing, thanks!
