### ISSUE TITLE
Feature Request:  Only display when in "Journals"

### ISSUE THREAD

**Issue by jpfieber** [karstenpedersen/obsidian-daily-note-navbar#2]
Works great on my Journals, but when I'm looking at other documents it shows incorrect dates and becomes useless.  I wonder if it's possible to add a setting for a folder where your journals are located, and then it only works when in that folder (shows default file path when viewing documents from other folders).

Bonus if you can automatically grab the 'Daily Notes' 'New file location' setting so it configures itself (you could get the 'Date format' for the note from there too, though the navigation still works even though the format isn't defined properly in your new beta version).

**Comment by karstenpedersen** [comment]
What other documents are you looking at (like their extensions and filenames)?

**Comment by jpfieber** [comment]
It would just be .md files.  I separate a lot of 'supporting' files like 'People' or 'Places' into their own folders since they each have different templates. People and Places, among others, don't have a 'this before that' order, so the navbar doesn't make sense on files in folders like that.  Seems like it would make sense to either have a setting that allows you to specify which folder (or I suppose some might use a tag or a property) to use to identify a 'daily-note'.  Since the Daily Notes plugin already has this setting, it could save end user effort to just apply the navbar on file in the Daily Notes location.  Make sense?

**Comment by karstenpedersen** [comment]
For me the navbar is removed when I open files that does not contain a date in the filename. I will look into this, but I'm having reproducing the scenario. I can maybe find it by looking at the code.

**Comment by jpfieber** [comment]
Actually, I just tried it again, and now it's working as you describe, not showing on non-journal notes, that way I would want/expect.  Never mind then, you're ahead of the game!

**Comment by karstenpedersen** [comment]
I think you were correct. There was a bug where the navbar was displayed, but it has been fixed in this PR: https://github.com/karstenpedersen/obsidian-daily-note-navbar/pull/4.
