### ISSUE TITLE
A question about PeriodicNote

### ISSUE THREAD

**Issue by Moyf** [karstenpedersen/obsidian-daily-note-navbar#20]
Hey, is there updates adding rely to "Periodic Notes" Plugin?

I have it but I recently disabled it.
And if I remember it correctly, it seems that DailyNote Navbar doesn't rely on it before? And now if I didn't turn the Periodic Note on, Navbar will show notice.

And I found out that for now if I open my Month Note, the navbar would also show up - seems that it recognize my "Month Note" as my "Daily Note (Today)"?
![image](https://github.com/karstenpedersen/obsidian-daily-note-navbar/assets/4013062/0d6da531-d8da-4913-88de-f7e95c6b8a13)

---

![image](https://github.com/karstenpedersen/obsidian-daily-note-navbar/assets/4013062/fb8c0ab7-4767-4e6e-96b8-6faa62e3b1b8)
 ↑ won't let me click on Today

**Comment by karstenpedersen** [comment]
What is your month note names?

**Comment by karstenpedersen** [comment]
Changed something, but I will enable Daily Notes to work again

**Comment by karstenpedersen** [comment]
Now the internal Daily Notes plugin works again. Sorry about that.

**Comment by Moyf** [comment]
> What is your month note names?

2024年6月

↑ means 2024 Year 6 Month

___

And just curious, how does this plugin know "this is a daily note" ? 🤔

**Comment by karstenpedersen** [comment]
Periodic notes plugin has an api that gives all the daily notes. 

I use it here:
https://github.com/karstenpedersen/obsidian-daily-note-navbar/blob/master/src%2Futils.ts#L80

It might be something with the characters. Can you send your daily note format and monthly note formats from Periodic Notes or Daily Notes, plus the format you have given this plugin.

This is so I can try and recreate it

**Comment by Moyf** [comment]
I'm also trying to replicate it.

And that's what I found:
![c1369c60-201b-400a-9808-3763aa3efaa1](https://github.com/karstenpedersen/obsidian-daily-note-navbar/assets/4013062/7aee6763-cf94-4cbf-97f4-2365a8f76c13)

It seems that if I open the Monthly Note from a link in Daily Note, the Navbar will stay (sometimes it would become double navbars).
And if I just open the Monthly Note in new tab, this issue won't appear.

---

Just found out that it's not related to "Monthly Note", any link open from Daily Note would keep the Navbar 🤔

**Comment by Moyf** [comment]
Also tried to open from other place (like Calendar) in Daily Note, and the navbar would also stay:
![2df1e3da-a8c6-47a7-8d79-a6aae326b9bf](https://github.com/karstenpedersen/obsidian-daily-note-navbar/assets/4013062/c8f09b64-a6c3-47f8-94c1-64ff924e41c0)

But I've got many other plugins enabled, so I'm not sure if it's due to some conflicts.
Let me know if this situation doesn't happen to you, and I'll try to address what is wrong.

Otherwise, maybe the plugin need to re-check when tab's content changes?

**Comment by karstenpedersen** [comment]
I can not get this to appear. I can't replicate your problem without information about how you have configured your daily and monthly notes, plus the daily notes plugin.

**Comment by Moyf** [comment]
> I can not get this to appear. I can't replicate your problem without information about how you have configured your daily and monthly notes, plus the daily notes plugin.

Roger that, here is my settings:
![image](https://github.com/karstenpedersen/obsidian-daily-note-navbar/assets/4013062/c1254caa-f36c-46d6-a3bd-669e89e469cc)
`YYYY-MM/YYYY-MM-DD`


## Periodic Note 
![image](https://github.com/karstenpedersen/obsidian-daily-note-navbar/assets/4013062/7750f966-2a2a-4f93-a7a4-8a23fc3113f4)
daily: `YYYY-MM/YYYY-MM-DD`
monthly: `YYYY年/YYYY年M月/YYYY年M月`

**Comment by karstenpedersen** [comment]
Hi I don't get this error using your settings. The navbar does not show up for the monthly notes or weekly notes, and it doesn't duplicate. This is both in my development vault, my own personal vault, and I have also tried in a new vault.

Could you try and uninstall Daily Note Navbar and install it again.

What platform/operating system are you on? and are you on the newest version of the plugin?

I'm grateful for your feedback on this problem

**Comment by Moyf** [comment]
> Hi I don't get this error using your settings. The navbar does not show up for the monthly notes or weekly notes, and it doesn't duplicate. This is both in my development vault, my own personal vault, and I have also tried in a new vault.
> 
> Could you try and uninstall Daily Note Navbar and install it again.
> 
> What platform/operating system are you on? and are you on the newest version of the plugin?
> 
> I'm grateful for your feedback on this problem

It's strange that now I can not replicate it, too 🤔

My system is: 
SYSTEM INFO:
	Obsidian version: v1.6.5
	Installer version: v1.5.12
	Operating system: Windows 10 Pro 10.0.22631
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Base theme: dark

plugin: Daily Note Navbar v0.2.0

Since this is a random bug, let's not worry about it for now. 
If there are further developments (such as a reliable way to reproduce it), I will come back  :D

**Comment by karstenpedersen** [comment]
Yeah, it is strange. Thanks a lot for the feedback. I think i need to reconsider how I push new versions. I should probably test them a bit more/think about the changes I make.
