### ISSUE TITLE
[FR] Adding mark for Tab of Today's Daily note?

### ISSUE THREAD

**Issue by Moyf** [karstenpedersen/obsidian-daily-note-navbar#22]
Now with Navbar plugin I can easily open several daily notes, thanks to your great work!

![image](https://github.com/user-attachments/assets/c6e0b034-f34f-4186-a2b8-143906db2bbc)
But sometimes I would open many daily notes and I have to think a while "which is today" (ooops)

What do you think adding a special mark in the Tab name for "Today"'s daily note, so that it could be easily distinguished from others? 
Could it be possible with plugin? 

---

![image](https://github.com/user-attachments/assets/8c922d60-51a1-4665-b879-cc48fd48048d)

For example, expose the "prefix" and/or "suffix" settings, so that users can adding special emoji..
Or, just adding a `css class` for the tab of today's daily note? 
Giving a default style, and users can override it thru the css snippets !

**Comment by karstenpedersen** [comment]
I have added this behavior, I just need to release it, but I have to look at something else before I do it.

The button for today has a unique class, which is: daily-note-navbar__current

https://github.com/karstenpedersen/obsidian-daily-note-navbar/issues/6

**Comment by Moyf** [comment]
Hahaha great! Waiting for the update  :D

**Comment by Moyf** [comment]
Oh wait a minute, I'm worried that I may not convey it clearly enough.

![image](https://github.com/user-attachments/assets/749b83e5-14cb-4e2f-a994-a9d3639c0d6b)
Would this workspace tab element also got the unique class?

**Comment by karstenpedersen** [comment]
Oh, I see. I can look into that.

How do you think this should work. Should this be toggleable in the settings?

We might also move away from functionality that fits the navbar. There could maybe be another plugin where the user could set icons for the tabs based on their filename.

It could maybe make sense to add it to a plugin like this: https://github.com/FlorianWoelki/obsidian-iconize. There might also be other plugins that already do this behavior. Have you looked into that?

**Comment by Moyf** [comment]
> Oh, I see. I can look into that.
> 
> How do you think this should work. Should this be toggleable in the settings?
> 
> We might also move away from functionality that fits the navbar. There could maybe be another plugin where the user could set icons for the tabs based on their filename.
> 
> It could maybe make sense to add it to a plugin like this: https://github.com/FlorianWoelki/obsidian-iconize. There might also be other plugins that already do this behavior. Have you looked into that?

Because this involves dynamic date checking rather than fixed strings, I am concerned that other plugins (usually based on specific names) may not have this level of granularity. I will try to find out!

**Comment by karstenpedersen** [comment]
I think this behavior should be in another plugin. It could be cool if one could add dynamic icons to tabs and/or files in the file tree.
