### ISSUE TITLE
[FR] Give buttons for previous and next notes

### ISSUE THREAD

**Issue by tariquesani** [karstenpedersen/obsidian-daily-note-navbar#23]
Thank you for this great plugin. I has helped me in decreasing clutter of navigation from my notes. It would be great if the Navbar could have dedicated button for previous and next daily notes. I have a streak of 13 years in journals which I have imported into Obsidian and am missing this feature.

**Comment by tariquesani** [comment]
For now I have implemented this functionality in my setup using the Quick Explore + Commander plugin

**Comment by karstenpedersen** [comment]
Good idea. I don't want to clutter the navbar by default, I could make the buttons toggleable or just create Obsidian commands, or both. What do you think?

**Comment by tariquesani** [comment]
> Good idea. I don't want to clutter the navbar by default, I could make the buttons toggleable or just create Obsidian commands, or both. What do you think?

Making both would be great. It gives flexibility to the user. Thank you. 🤩

**Comment by karstenpedersen** [comment]
Hi, I don't think I want to add this to this plugin, as I want this plugin to focus on the navbar.

You can add it yourself by using [Commander](https://github.com/phibr0/obsidian-commander) and [Periodic Notes](https://github.com/liamcain/obsidian-periodic-notes)

![image](https://github.com/user-attachments/assets/80f98fa1-4858-4b51-b5fa-e421699a9399)

![image](https://github.com/user-attachments/assets/52d2da84-9b49-4fdb-9b15-d8214b84ca10)


They also have commands for weeks, months and years
