### ISSUE TITLE
Feature Request: hotkeys for navigation

### ISSUE THREAD

**Issue by drakeguan** [karstenpedersen/obsidian-daily-note-navbar#3]
This plugin just works for me. The coloring for different daily notes (the active, the other, and the missing) is also quite ok to me. Love this compact and useful plugin.

One further idea is to provide customizable hotkeys for navigation, like "Previous existing daily note" and "Next existing daily note". Then both mouse-lover and hotkey-maniac can both benefit and enjoy this plugin :)

Cheer~

**Comment by karstenpedersen** [comment]
I like this idea, but I need to think about if it fits the functionality this plugin. It could maybe be its own plugin, as it doesn't really have anything to do with the navbar. There could also be more commands, which the user could customize themselves.

Glad you like this plugin :)
