### ISSUE TITLE
Cannot get plugin to appear

### ISSUE THREAD

**Issue by jordanlong121** [karstenpedersen/obsidian-daily-note-navbar#5]
I installed and enabled the plugin but it will not appear in existing or new daily notes.  My daily notes use a custom value, which I matched in the plugin settings. That didn't work, so I set my Daily Notes plugin to use the default value, as well as the default value in the nav plugin, with no luck. Any ideas? I'm running the latest Catalyst version of Obsidian.

**Comment by karstenpedersen** [comment]
Are you using a theme? That might affect how the plugin works.

**Comment by karstenpedersen** [comment]
Can you also give the format your daily notes use, just so I can see. But I don't think it is that, if even the default values doesn't work.

**Comment by jordanlong121** [comment]
I created a new vault and the plugin does work with my custom daily note format, YYYY-MM-DD (dddd), so it's something to do with my specific vault setup.

**Comment by jordanlong121** [comment]
After deleting by .obsidian folder  and re-installing my plugins, the navbar plugin continues to work. It must have been some previous hack or left-over theme that was breaking it. Thank you for the help, it's a great plugin!

**Comment by karstenpedersen** [comment]
Good to hear :)

Feel free to write if you find more issues.
