### ISSUE TITLE
Feature Request: Add some indication of today

### ISSUE THREAD

**Issue by machado-t** [karstenpedersen/obsidian-daily-note-navbar#6]
Please consider adding some kind of visual indication (underlining? different color?) of which day is today.
Thanks!

**Comment by karstenpedersen** [comment]
The plugin changes the color of the current date to the primary color. Can you send a screenshot, and are you using a theme or CSS snippets?

**Comment by karstenpedersen** [comment]
It's the purple one here. It is an old screenshot,  so the date is not today's date.

![Screenshot_20240409_194648_Chrome.jpg](https://github.com/karstenpedersen/obsidian-daily-note-navbar/assets/53978294/e8c08b9e-5d21-42b7-8f52-156d0c997cfa)

**Comment by machado-t** [comment]
Sorry I wasn't too clear. 
The accent color represents the open daily note - not today's.
My suggestion is some additional indication on which day is today.

**Comment by karstenpedersen** [comment]
I'm not sure I understand. You could send a screenshot on how it looks in your vault if it's different, or maybe make a drawing if you want a new thing.

**Comment by karstenpedersen** [comment]
I'm sorry, I forgot what styling I have added to the plugin. I understand your suggestion now. I will probably add an underline to the actual "today's note".

**Comment by karstenpedersen** [comment]
Hi, I have updated the plugin and added the CSS class "daily-note-navbar__current" to the element that represents the current date. https://github.com/karstenpedersen/obsidian-daily-note-navbar/releases/tag/0.1.4

You could write a [CSS snippet](https://help.obsidian.md/Extending+Obsidian/CSS+snippets) to add an underline like this:

```css
.daily-note-navbar__current {
    text-decoration: underline;
}
```
